### ISSUE TITLE
Timeout error as well

### ISSUE THREAD

**Issue by awieland01** [alduzzen1985/Audit-History-Extractor#10]
We are receiving a timeout error and it seems your code need to increase the timeout from 2 minutes,  to resolve this issue, can you please respond and let us know if this can be accomplished
[5-23-2019 10-21-47 AM](https://user-images.githubusercontent.com/50956858/58260991-77584600-7d45-11e9-9ae3-14d7d42bbbea.jpg)

**Comment by alduzzen1985** [comment]
you can extend the service timeout in the connection details 

![image](https://user-images.githubusercontent.com/32884589/59391270-b6d5e900-8d6b-11e9-8d40-e375205af371.png)
