### ISSUE TITLE
Not Able to use it

### ISSUE THREAD

**Issue by Sahil6309243** [alduzzen1985/Audit-History-Extractor#11]
How do i use it ?

I have open it in Visual Stuido 2015 but its giving me error of Startup Project error.
![Capture](https://user-images.githubusercontent.com/51310708/58777886-0e4abb00-85ee-11e9-9644-ab559789e52b.PNG)

**Comment by alduzzen1985** [comment]
Try to execute the application in Debug Mode and follow this tutorial https://www.xrmtoolbox.com/documentation/for-developers/debug/
