### ISSUE TITLE
Version dependency incorrect

### ISSUE THREAD

**Issue by rappen** [alduzzen1985/Audit-History-Extractor#13]
Hi, latest version states a dependency on XrmToolBox 2.2019.6.11.
https://www.nuget.org/packages/AuditHistoryExtractor/

This makes it appear as incompatible in the Plugins Store as the XTB version is currently **1**.2019.6.33.

![image](https://user-images.githubusercontent.com/2572253/59374722-c560d800-8d4c-11e9-9253-43ec128cd644.png)

**Comment by iggsn** [comment]
Should be fixed with my Pull Request #21 
This also includes the code to export history for more than 5.000 records.

**Comment by alduzzen1985** [comment]
Thanks,

I've fixed both problems.
