### ISSUE TITLE
Showing "All Fields changed" uses the first ColumnSet values for all subsequent ColumnSets

### ISSUE THREAD

**Issue by RedsGT** [alduzzen1985/Audit-History-Extractor#15]

**Comment by RedsGT** [comment]
For example if the first OptionSet is {[0, Blue][1, Red][2, Green]} but the second is {[0, square][1, circle][2, triangle][3, cube]} and for the second dataset you expect "square" and "cube" you get "blue" and "N/A".

**Comment by RedsGT** [comment]
![image](https://user-images.githubusercontent.com/1190796/63905078-aa5f4500-c9d8-11e9-8b77-02f1fb19ba8e.png)

**Comment by RedsGT** [comment]
![Capture5](https://user-images.githubusercontent.com/1190796/63905438-e5ae4380-c9d9-11e9-855d-d3d109985e85.PNG)

**Comment by alduzzen1985** [comment]
This problem should have been fixed. Please get the last version.

![image](https://user-images.githubusercontent.com/32884589/73534020-01e65e80-4418-11ea-98bd-6768c22068e4.png)
