### ISSUE TITLE
RecordKeyValue is not shown when new value is empty

### ISSUE THREAD

**Issue by rtett** [alduzzen1985/Audit-History-Extractor#17]
Because auditHistory.RecordKeyValue is not set in the second foreach, history records where the new value is empty are missing the value of the key. I propose adding the following line just before String newValue = "(no value)";

                    auditHistory.RecordKeyValue = recordKeyValue;

**Comment by alduzzen1985** [comment]
In the last version, I've added the Record ID so I think is better keep the value empty.

![image](https://user-images.githubusercontent.com/32884589/73533838-a3b97b80-4417-11ea-8240-73ff9bfd896c.png)
