### ISSUE TITLE
It would be helpful to have the record ids exported along with the history.

### ISSUE THREAD

**Issue by rtett** [alduzzen1985/Audit-History-Extractor#18]
I propose adding the following to the AuditHistoryRecordMap as the first line of the constructor:

            Map(m => m.RecordId).Name("Record ID");

**Comment by alduzzen1985** [comment]
Hi, thanks for your suggestion.
I've included the change in the last release.

![image](https://user-images.githubusercontent.com/32884589/73533790-88e70700-4417-11ea-83ad-fe726007ce93.png)
