### ISSUE TITLE
The Global Option set value is shown as N/A in New Value

### ISSUE THREAD

**Issue by kubhaskar1** [alduzzen1985/Audit-History-Extractor#20]
When I extract the contact entity data I am all the Global Option set values are shown as N/A in New Value. What should I do to display the actual option set value.
![Error_Option set Value](https://user-images.githubusercontent.com/49396384/65680902-8ba2ab80-e075-11e9-9fda-931f101eb0fc.PNG)

**Comment by kleziegler** [comment]
Same issue here. But the real problem is, that the option set values are mixed up. 
E.g. inactive is shown as active and active as N/A.

This does only happen, if you export all fields. When you export only a specific field this does not happen.

**Comment by kleziegler** [comment]
Should be fixed with #22

**Comment by alduzzen1985** [comment]
I've included your change in the last release. Many thanks for your support.
 
![image](https://user-images.githubusercontent.com/32884589/73533751-6ead2900-4417-11ea-8319-45bd5a44ddf0.png)
