### ISSUE TITLE
I don't see Audit History Extractor inside Plugins tab of lastest XrmToolbox 

### ISSUE THREAD

**Issue by DavidPezzoli** [alduzzen1985/Audit-History-Extractor#23]
Hi, 
I don't see Audit History Extractor inside Plugins tab of lastest XrmToolbox. I installed it....

![image](https://user-images.githubusercontent.com/45006314/73254189-37900b00-41be-11ea-93a1-376f7ae562a3.png)

![image](https://user-images.githubusercontent.com/45006314/73254268-5f7f6e80-41be-11ea-8490-3df995efcedc.png)

Please, How to enable it  in order to login and use it?

Thx,
David

**Comment by pblbsyl** [comment]
I am having the same issue.  I click Install in XrmToolbox, and it appears to install.  However, it stays greyed out on the tool list and is not available to open.  Any idea what we need to do to correct?  Thank you for your help.

**Comment by alduzzen1985** [comment]
Hi All,
I've had a problem with the release of the Plugin. Should be released in few hours.

**Comment by alduzzen1985** [comment]
Guys, you can download the new version. Has been released.

![image](https://user-images.githubusercontent.com/32884589/73533694-56d5a500-4417-11ea-9bdd-433b8c3ba898.png)

**Comment by pblbsyl** [comment]
Thank you so much for your fast reply.  Appreciate it.
