### ISSUE TITLE
audit history extractor not exporting all records

### ISSUE THREAD

**Issue by chunkingz** [alduzzen1985/Audit-History-Extractor#25]
I have just recently come across your tool, when I select any entity, tick the fetchXML radio button and click export, I get around 200+ rows, and in my audit summary view in Dynamics 365 I can see that I have about 5000+ rows.

Please how can I make it export the complete data or is this a limitation in the tool?

I am on the latest version of the audit history extractor and xrmtoolbox.

**Comment by EW-C** [comment]
I have noticed that it does not include all audit records too when comparing the output with the Attribute Audit Explorer tool for the Xrmtoolbox.

Maybe this is something to do with the views/filtering? This is a really useful tool and it would be great if someone was able to fix this!

**Comment by Roxxinger** [comment]
I think this tool only exports the AttributeAuditDetail, so no RelationshipAuditDetail, RolePrivilegeAuditDetail, ShareAuditDetail, UserAccessAuditDetail etc. is fetched/exported.
Thats causing the difference i guess.

**Comment by alduzzen1985** [comment]
Hi,

the new version in the Log Tab, inform you if no audit history changes are available.

Yes, the plugin extracts only the Attribute Changes.
