### ISSUE TITLE
timeout on contact records

### ISSUE THREAD

**Issue by kateriley** [alduzzen1985/Audit-History-Extractor#26]
Hello, 

I get the following errors. I updated the timeout window to 5 and then 10 but still get the error. I only get this error for contact records. Do you know what could be causing this? 

![image](https://user-images.githubusercontent.com/32334098/98408380-127ad380-203f-11eb-913b-25b40401c123.png)

Thanks so much for the tool, and hoping I can figure out the issue as we use it often.

Cheers!
Kate

**Comment by alduzzen1985** [comment]
Hi Kate,

would you be able to try with the new version and let me know?

Thanks

**Comment by ugacodedawg** [comment]
Hello.
Having the same issue but on Opportunity records.  This was happening with the version 2.2020.1.30, and still is happening after upgrading to 2.2020.12.30.  Clicking Preview Data starts to run the records, but then freezes after the first one.  Microsoft says they don't support 3rd party tools and maintain that everything looks okay with the entity from their side.  This is the only entity that has problems...able to export others with no problems.  Thoughts?  Thanks!

**Comment by kateriley** [comment]
Hello,

Sorry for the delay. The new version is working for me now.

Thank you!
Kate

**Comment by alduzzen1985** [comment]
Please update to the last version.

Regards,

Aldo
