### ISSUE TITLE
Error about a floating point exeption

### ISSUE THREAD

**Issue by mvdtogt** [alduzzen1985/Audit-History-Extractor#28]
Since the new options are introduced in the AuditHistoryExtractor I get this error: "The database engine received a floating point exeption from the operating system while processing a user request. Try the transaction again. If the problem persists, contact your system administrator".
I am the system administrator and I don't know what to do. Is this a bug or has it something to do with our CRM?

**Comment by alduzzen1985** [comment]
Hi,

Did you get the error message when you try to extract a preview or to Save in the Excel File ?

How many records do you have approximately ?

**Comment by mvdtogt** [comment]
Hi Aldo,

I never use the preview. I always directly click on the button "Export tot SCV".
It concerns about 6.500 account records
I filtered only Updates
I filtered just one User
I filtered just 2 fields
I filtered a date range of 3 months.

With or without the filters, I get the same error
[cid:image001.jpg@01D6FDF0.3BF971B0]

Kind regards,
Martin.

Van: Aldo G. <notifications@github.com>
Verzonden: zondag 7 februari 2021 13:04
Aan: alduzzen1985/Audit-History-Extractor <Audit-History-Extractor@noreply.github.com>
CC: Togt, Martin van der <martinvandertogt@royalfloraholland.com>; Author <author@noreply.github.com>
Onderwerp: Re: [alduzzen1985/Audit-History-Extractor] Error about a floating point exeption (#28)


Hi,

Did you get the error message when you try to extract a preview or to Save in the Excel File ?

How many records do you have approximately ?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falduzzen1985%2FAudit-History-Extractor%2Fissues%2F28%23issuecomment-774663093&data=04%7C01%7Cmartinvandertogt%40royalfloraholland.com%7C5bceee58d5794c41f82708d8cb60696b%7Ce6c9e26f345f436fa5d004b2314a82c4%7C0%7C0%7C637482962232617561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SOPeLLfwGOst8ISEF8AxY8%2Be2wFi%2BOl8HPsMWekneFg%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKFI7SH5FJAWVW5CSJSC7SLS5Z6RZANCNFSM4XEGE5BA&data=04%7C01%7Cmartinvandertogt%40royalfloraholland.com%7C5bceee58d5794c41f82708d8cb60696b%7Ce6c9e26f345f436fa5d004b2314a82c4%7C0%7C0%7C637482962232617561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QCvqN4I6qKsw2z2IXb3XUjcp0emv2qqDsUaZ9FDRuWk%3D&reserved=0>.

Dit e-mailbericht is verzonden namens de Co?peratie Royal FloraHolland U.A., statutair gevestigd te Aalsmeer, kamer van koophandel nr. 34284016 (hierna: 'Royal FloraHolland'). De informatie in dit e-mailbericht is uitsluitend bestemd voor de geadresseerde en kan vertrouwelijk en/of privacygevoelig zijn. Royal FloraHolland kan niet instaan voor de bevoegdheid van de afzender noch voor de inhoud van dit bericht of de overbrenging daarvan en kan niet garanderen dat dit bericht vrij is van virussen. Op alle verbintenissen met Royal FloraHolland is het Veilingreglement van toepassing. Het Veilingreglement is gedeponeerd bij de griffie van de rechtbank Amsterdam nr.32/2020 en gepubliceerd op de website www.royalfloraholland.com.

**Comment by alduzzen1985** [comment]
Hey, 

sorry for my late answer. If you click the Preview is it working?

Thanks

**Comment by mvdtogt** [comment]
Hello Aldo,

The Preview is working and comes with results pretty quick (a few minutes). That means when you use the right filter. I wanted the changes made by a particular user, in a particular field. It seams that the preview respects the field filter, but looks at the user filter as to be the last user who made the change. And I want all changes made by that user in a field.
So when I delete the filter on the User, I get the right result.

When I click on "Export to CSV", it takes a tremendous long time (over 6 hours!) to export the result. It seams not to use the previewed data but to generate them again, based on the filters.

The result of the export contains the data I need. Only the changes on a particular field, but from all users.

Over 27.000 thousand record. And now no errors.

Vriendelijke groet,
Martin.

Van: Aldo G. <notifications@github.com>
Verzonden: woensdag 24 februari 2021 17:03
Aan: alduzzen1985/Audit-History-Extractor <Audit-History-Extractor@noreply.github.com>
CC: Togt, Martin van der <martinvandertogt@royalfloraholland.com>; Author <author@noreply.github.com>
Onderwerp: Re: [alduzzen1985/Audit-History-Extractor] Error about a floating point exeption (#28)


Hey,

sorry for my late answer. If you click the Preview is it working?

Thanks

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falduzzen1985%2FAudit-History-Extractor%2Fissues%2F28%23issuecomment-785181704&data=04%7C01%7Cmartinvandertogt%40royalfloraholland.com%7C7fa13d89757e4f7300ed08d8d8ddae21%7Ce6c9e26f345f436fa5d004b2314a82c4%7C0%7C0%7C637497793921226671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9KdWeCJZGB2DLpUMZSjdpHAA%2BPX9CoWLu82yPiwegAw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKFI7SA57SADE24PF56GZALTAUPLZANCNFSM4XEGE5BA&data=04%7C01%7Cmartinvandertogt%40royalfloraholland.com%7C7fa13d89757e4f7300ed08d8d8ddae21%7Ce6c9e26f345f436fa5d004b2314a82c4%7C0%7C0%7C637497793921236626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NliEgBH11k0%2Fq%2B353eJT9tqvOCD6tsJxowJ0Bvyqwq0%3D&reserved=0>.

Dit e-mailbericht is verzonden namens de Co?peratie Royal FloraHolland U.A., statutair gevestigd te Aalsmeer, kamer van koophandel nr. 34284016 (hierna: 'Royal FloraHolland'). De informatie in dit e-mailbericht is uitsluitend bestemd voor de geadresseerde en kan vertrouwelijk en/of privacygevoelig zijn. Royal FloraHolland kan niet instaan voor de bevoegdheid van de afzender noch voor de inhoud van dit bericht of de overbrenging daarvan en kan niet garanderen dat dit bericht vrij is van virussen. Op alle verbintenissen met Royal FloraHolland is het Veilingreglement van toepassing. Het Veilingreglement is gedeponeerd bij de griffie van de rechtbank Amsterdam nr.32/2020 en gepubliceerd op de website www.royalfloraholland.com.

**Comment by alduzzen1985** [comment]
Please update to the last version.

Regards,

Aldo
