### ISSUE TITLE
Plugin Stop responding

### ISSUE THREAD

**Issue by gibbo22** [alduzzen1985/Audit-History-Extractor#29]
Hi,

Issue: The plugin 'Audit-History-extractor' stops responding when extracting data larger that 200kb

This has been an issue since I have updated to the version 2.2020.12.30 and I am unable to rollback.  I have had 1 other developer from my team run into this issue also.

We have already exported 24GB of data from our D365 environment, this version update which is now blocking the last 20GB of data to export.  
I am wondering if this is affecting multiple other people also and it hasn't been raised yet?  

Any support is really appreciated here!

Kind regards,
Jacob

**Comment by alduzzen1985** [comment]
Hi Jacob,

soon I'll release a hotfix for this problem. If you want to test the new version contact me on [Linkedin](https://www.linkedin.com/in/aldogillone/).

Thanks,

Aldo

**Comment by alduzzen1985** [comment]
Please update to the last version.

Regards,

Aldo
