### ISSUE TITLE
Can't see bottom half of right side.

### ISSUE THREAD

**Issue by DebSil** [alduzzen1985/Audit-History-Extractor#3]
Can't see bottom half of pane on right side to execute the plugin.
<img width="409" alt="auditextractor" src="https://user-images.githubusercontent.com/9323672/36493631-0b7f1e1c-16fe-11e8-86df-805d081a9066.png">

**Comment by alduzzen1985** [comment]
Hi DebSil, get the last version (10.0.1.14). The problem should be okay.
