### ISSUE TITLE
Given key not present in the dictionary

### ISSUE THREAD

**Issue by inneslu** [alduzzen1985/Audit-History-Extractor#30]
Latest update has broken the plugin v2.2021.7.28
Getting a 'The given key was not present in the dictionary' when trying to preview data / export to csv.

Had a brief look at the commit history - looks like the issue could be in AuditHistoryManager.
The GetRecordChanges method is using attributeDetail.OldValue[attribute.Key]. There is no check to see if OldValue contains the key.

**Comment by AlexanderRuiter** [comment]
Confirmed. Same error. Where can I find the non-Beta/ previous and how can I use that? We need this urgent.

**Comment by navneethpandian** [comment]
![image](https://user-images.githubusercontent.com/17922835/127469630-6eeaeb40-9bee-4de4-b622-4d60f17cdcaf.png)
Same error message. Please help ! any alternate approach?

**Comment by DianaTejeda** [comment]
I am also getting that error. Is there a way to download the previous version? 
Thanks in advance for your help!

**Comment by AsianMike24** [comment]
Same error, where can I find older versions?

**Comment by maloadca** [comment]
# issues cannot convert Data Type in the source code:
1. bool isTypeOptionSet = attributeDetail.OldValue[attribute.Key] is OptionSetValue;
2. bool isOldValueAnEntityReference = attributeDetail.OldValue[attribute.Key] is EntityReference;
#Fixed: 
 bool isTypeOptionSet = false;
                    try
                    {
                        isTypeOptionSet = attributeDetail.OldValue[attribute.Key] is OptionSetValue;
                    }
                    catch { }
                    bool isOldValueAnEntityReference = false;
                    try
                    {
                        isOldValueAnEntityReference = attributeDetail.OldValue[attribute.Key] is EntityReference;
                    }
                    catch { }

**Comment by alduzzen1985** [comment]
Hi Guys,

sorry for the issue. I've just deployed the fix.

Regards

**Comment by alduzzen1985** [comment]
Please update to last version
