### ISSUE TITLE
NO data exported

### ISSUE THREAD

**Issue by brichardson2013** [alduzzen1985/Audit-History-Extractor#8]
After creating the FETCH, and then attempting to export the data from the audit log, I ended up with a csv file that was empty except for the headers.  No matter what I do, I get a 1KB file.  I'm using VS 2017 and Dynamics v 9.02

**Comment by alduzzen1985** [comment]
Hi,
can you Try to get the last version please ?

![image](https://user-images.githubusercontent.com/32884589/73533922-d3688380-4417-11ea-8a27-801c7fad84f4.png)
