### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by rmcanally** [alduzzen1985/Audit-History-Extractor#9]
I am trying to extract (in this instance, the field Account Name (name)) but constantly receive the following error; is there any settings, etc. I can manipulate to avoid said error?

![audit extractor error 01](https://user-images.githubusercontent.com/12864209/53039832-abba1e80-3445-11e9-9819-38cadb151b76.PNG)

"The request channel timed out while waiting for a reply after 00:02:00.  Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

**Comment by alduzzen1985** [comment]
You can extend the Service Time  in the settings of your connection. 

![image](https://user-images.githubusercontent.com/32884589/59391240-a1f95580-8d6b-11e9-8913-3c3399aa5da2.png)
